### ISSUE TITLE
pre-commit 4.0.0: InvalidManifestError

### ISSUE THREAD

**Issue by cesarcoatl** [PyCQA/docformatter#289] opened 2024-10-06 02:09 UTC
My `.pre-commit-config.yaml` includes the following:

```yaml
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=72, --close-quotes-on-newline]
```

Error:

```sh
$ pre-commit run --all-files                                                          
An error has occurred: InvalidManifestError: 
==> File /Users/cesarcoatl/.cache/pre-commit/repoffw0ifit/.pre-commit-hooks.yaml
==> At Hook(id='docformatter-venv')
==> At key: language
=====> Expected one of conda, coursier, dart, docker, docker_image, dotnet, fail, golang, haskell, lua, node, perl, pygrep, python, r, ruby, rust, script, swift, system but got: 'python_venv'
Check the log at /Users/cesarcoatl/.cache/pre-commit/pre-commit.log
```

The problematic line of YAML can be found here:

https://github.com/PyCQA/docformatter/blob/886a0329b3949dfb8be9f10f80bc96829923debe/.pre-commit-hooks.yaml#L13

Possible solution:

Fix hook

**Comment by asottile** [comment] 2024-10-07 14:38
please don't mention me when you can read the docs it has been a warning and alias for years

**Comment by webknjaz** [comment] 2024-10-07 14:40
@asottile fair, sorry. Do you have a commit bit to merge https://github.com/PyCQA/docformatter/pull/287, though?

**Comment by asottile** [comment] 2024-10-07 21:38
> @asottile fair, sorry. Do you have a commit bit to merge #287, though?

I do, but only because I'm an org admin so it doesn't seem right for me to do it :S

**Comment by weibullguy** [comment] 2024-10-09 18:23
Fixed in PR #290.

**Closed by weibullguy** 2024-10-09 18:23 UTC
Labels: P: enhancement, C: stakeholder, U: low

**Comment by s-weigand** [comment] 2024-10-10 19:40
For anyone who still has this issue.
`pre-commit` supports defining specific commits out of the box so just use the fix commit 06907d0 (in the end tags are just flippy floppy pointers to commits anyway 😅)

```py
  - repo: https://github.com/PyCQA/docformatter
    rev: 06907d0
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
```

**Comment by webknjaz** [comment] 2024-10-10 22:58
> ```yaml
> rev: 06907d0
> ```

Does this work? I remember some tooling only allowing full commit hashes and being unhappy about the short ones.

**Comment by nfelt14** [comment] 2024-10-13 23:14
> Fixed in PR #290.

It may be fixed in the default branch, but there isn't a release available with the fix yet.

**Comment by fepegar** [comment] 2024-10-16 21:17
> Does this work?

Yes.

**Comment by crypdick** [comment] 2024-11-13 22:02
> > rev: 06907d0
> 
> Does this work? I remember some tooling only allowing full commit hashes and being unhappy about the short ones.

I can confirm this works.
