### ISSUE TITLE
Invalid removal of black lines for function with only a docstring

### ISSUE THREAD

**Issue by Sillocan** [PyCQA/docformatter#173] opened 2023-04-04 23:31 UTC
Using `docformatter==1.6.0`, all blank lines are removed after a function with only a single line docstring.

i.e.
```py
"""Here are some examples.

This module docstring should be dedented.
"""


def launch_rocket():
    """Launch the rocket."""

def factorial(x):
    """Return x factorial.

    This uses math.factorial.
    """
    import math
    return math.factorial(x)
```

is being parsed to

```py
"""Here are some examples.

This module docstring should be dedented.
"""


def launch_rocket():
    """Launch the rocket."""
def factorial(x):
    """Return x factorial.

    This uses math.factorial.
    """
    import math
    return math.factorial(x)
```

This seems like a regression

**Comment by tekumara** [comment] 2023-04-05 07:46
Related example:
```
+++ b/src/aec/util/configure.py
@@ -8,7 +8,6 @@ from importlib_resources.abc import Traversable
 
 def example() -> None:
     """create example config files in ~/.aec/."""
-
     config_dir = os.path.expanduser("~/.aec/")
     os.makedirs(config_dir, exist_ok=True)
```

**Comment by hofbi** [comment] 2023-04-11 11:35
Could be a duplicate of https://github.com/PyCQA/docformatter/issues/156

**Closed** 2023-04-12 22:54 UTC
Labels: P: bug, C: convention

**Comment by weibullguy** [comment] 2023-04-12 23:02
@Sillocan tag v1.6.1-rc1 should have the fix you need if you're interested in giving it a try before I officially release v1.6.1.

**Comment by Sillocan** [comment] 2023-04-12 23:57
Worked like a charm!
