### ISSUE TITLE
Bug: Multi-line summary has closing quotes on the same line

### ISSUE THREAD

**Issue by howeaj** [PyCQA/docformatter#84] opened 2022-05-05 21:49 UTC
Docformatter's readme states that it follows the following PEP 257 item:

> Unless the entire docstring fits on a line, place the closing quotes on a line by themselves.

But it doesn't; it only places the closing quotes on a line by themselves if there is a description (or if the option `--make-summary-multi-line` is specified, but then it puts the opening quotes on a separate line too)

i.e. with default arguments it formats this:

```
"""Loooooooooooooooooooooooooooooooooong summary line that will get wrapped to multiple lines."""
```

to this:

```
"""Loooooooooooooooooooooooooooooooooong summary line that will get
wrapped to multiple lines."""
```

when it should instead format to this:

```
"""Loooooooooooooooooooooooooooooooooong summary line that will get
wrapped to multiple lines.
"""
```

**Comment by weibullguy** [comment] 2022-07-24 16:05
Per [PEP-257](https://peps.python.org/pep-0257/#one-line-docstrings), one-line docstrings _should_ fit on a single line including the triple quotes.  Placing the closing triple quotes on a new line is for multi-line docstrings.  It seems the PEP-257 preferred solution would be to shorten the docstring to fit on a single line.

The `--wrap-summaries` argument can be used to set the point at which docformatter breaks the line if there's a need to accommodate lines longer than 79 characters.  However, placing the closing triple quotes in-line with a one-line docstring, even a really long one, is in accordance with PEP-257. Thus, this behavior is not a bug.

This issue is a duplicate to #9 which is to be addressed by #49.  Closing to #9.

**Closed by weibullguy** 2022-07-24 16:05 UTC
Labels: duplicate
